import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/components/providers/ConvexClientProvider";
import Silk from "@/components/Silk";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ConvexClientProvider>
            <div className="min-h-screen text-gray-100 flex flex-col">
              <div className="fixed inset-0 -z-10">
                <Silk
                  speed={5}
                  scale={0.6}
                  color="#363536"
                  noiseIntensity={1.5}
                  rotation={0}
                />
              </div>

           <div className="relative z-10">
                {children}
              </div>
            </div>
          </ConvexClientProvider>

          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  );
}